### ISSUE TITLE
[docs] Docs for contribution guide

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/swim#11]
Branch, Merge, Commit, PR, etc
We need some contribution guide docs.

**Comment by hihiboss** [comment]
브랜치 관리, 머지, 커밋단위, 풀리퀘 등에 대한 의논이 필요해보입니다.

**Comment by junbeomlee** [comment]
We already had contributing file(https://github.com/DE-labtory/swim/blob/develop/CONTRIBUTING.md). But let me know if you have anything to update.
