### ISSUE TITLE
[cmd] Add cli with github.com/urfave/cli

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/swim#18]
Global option
 - `swim --config <config> or -c <config> [subcommand]`
 - `swim --debug or -d [subcommand]`

Subcommand will be 
 - `swim start [--address <ip:port>] `
 - `swim add member [--address <ip:port>]`

**Comment by junbeomlee** [comment]
Any other suggestions?

**Comment by hihiboss** [comment]
In subcommand, how about
`swim [command] [--address <ip:port>]`
rather than
`swim [command] [--ip <ip:port>]`
?

**Comment by junbeomlee** [comment]
Then
 - `swim start [--address <ip:port>] `
 - `swim add [--address <ip:port>]`
?

**Comment by zeroFruit** [comment]
How about `swim join` instead of `swim add` ?
Join to (existing) network

**Comment by junbeomlee** [comment]
LGTM
