### ISSUE TITLE
[env] CLA hub bug

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/swim#22]
**Where**
CLA hub

**Bug detail**
When a PR is generated, CLA hub doesn't work although signed to CLA hub.

**Fix plan**
fix it plz

**Reference**
.

**Comment by zeroFruit** [comment]
@junbeomlee plz check the repo settings

This two links may help fix the bug

* https://github.com/clahub/clahub/issues/133#issuecomment-226336855
* https://circleci.com/docs/2.0/workflows-waiting-status/

**Comment by junbeomlee** [comment]
fixed!
