### ISSUE TITLE
[docs] writing more about suspicion mechanism 

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/swim#32]
I'm interested in suspicion mechanism so I'm now investigating more about this, so before move on to "writing codes", I think it is better to write down docs more about suspicion mech.

**Comment by AgwaB** [comment]
you mean you want to write docs not only about in SWIM Thesis , also about other things?

**Comment by zeroFruit** [comment]
no, suspicion mechanism based on SWIM paper and on #31

**Comment by zeroFruit** [comment]
Please feedback about #34 integrating Lifeguard concept
