### ISSUE TITLE
structure

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/swim#40]
**Subject**
All of members

**Proposal Detail**
I think in hashicorp's memberlist struct `Memberlist` do too much things, so I think it is better to separate responsibility. My suggestion is.. I want to separate receiving message part and sending message part. So the structure is

![screenshot from 2018-11-12 12-54-41](https://user-images.githubusercontent.com/18715362/48325700-42728480-e67a-11e8-9a1b-cbef71d641d2.png)

- Spaceship (this is Memberlist in hashicorp, and temporarily named it :), and network as galaxy..)
  - MessageTransmitter
  - MessageReceiver
  - ...

**Comment by zeroFruit** [comment]
@junbeomlee @leesd556 @hihiboss

**Comment by junbeomlee** [comment]
I agree with that `I think in hashicorp's memberlist struct Memberlist do too much things,`
But also you might also need to consider implementing a transmitter and a receiver as a single struct.
